### ISSUE TITLE
Treat 8:1 and 1:8 ratios differently

### ISSUE THREAD

**Issue by VolatileDream** [xXastaspastaXx/Dimensions#7]
Because of the logic in [`CustomPortal:getRatio`](https://github.com/xXastaspastaXx/Dimensions/blob/master/src/main/java/me/xxastaspastaxx/dimensions/portal/CustomPortal.java#L272-L273) using `8:1` and `1:8` ratios behaves identically.

It would be expected that one of these behaves like the nether (1:8), and the other behaves the opposite (8:1). Especially when the [custom portal editor](https://astaspasta.alwaysdata.net/creator/index) suggests that this is the case.

This is a really simple fix: [`CustomPortal:getRatio`](https://github.com/xXastaspastaXx/Dimensions/blob/master/src/main/java/me/xxastaspastaxx/dimensions/portal/CustomPortal.java#L266-L274) needs to be modified to return `double` instead (to represent X:Y ratios where X > Y), and the `if` statement removed.

Note: clients may be using `X:1` or equivalent, and not know that it's behaving unexpectedly. Meaning that changing the behaviour would be a world incompatible change.

**Comment by xXastaspastaXx** [comment]
Thank you for your feedback. Actually, that method was supposed to return double. The reason it's not doing that is because of me not testing stuff enough to figure out I forgot to change it :/
Anyway, the whole method is a mess and since the plugin is being rewritten. It has been modified and is exactly as you suggested above.
Thank you for your help and sorry for the very late reply
